from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
cities = ['Alba Iulia',
          'Alexandria',
          'Arad',
          'Bacău',
          'Baia Mare',
          'Bistriţa',
          'Botoşani',
          'Braşov',
          'Brăila',
          'Bucharest',
          'Buzău',
          'Cluj-Napoca',
          'Constanţa',
          'Craiova',
          'Călăraşi',
          'Deva',
          'Drobeta-Turnu Severin',
          'Focşani',
          'Galaţi',
          'Giurgiu',
          'Hunedoara',
          'Iaşi',
          'Miercurea-Ciuc',
          'Oradea',
          'Piatra Neamţ',
          'Piteşti',
          'Ploieşti',
          'Reşiţa',
          'Râmnicu Vâlcea',
          'Salcia',
          'Satu Mare',
          'Scheia',
          'Sfântu-Gheorghe',
          'Sibiu',
          'Slatina',
          'Slobozia',
          'Suceava',
          'Timişoara',
          'Tulcea',
          'Târgovişte',
          'Târgu Jiu',
          'Târgu-Mureş',
          'Vaslui',
          'Zalău'
          ]
