from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
cities = ['Alba Iulia',
          'Alexandria',
          'Arad',
          'Bacau',
          'Baia Mare',
          'Bistriţa',
          'Botosani',
          'Brasov',
          'Braila',
          'Bucharest',
          'Buzau',
          'Cluj-Napoca',
          'Constanta',
          'Craiova',
          'Calarasi',
          'Deva',
          'Drobeta-Turnu Severin',
          'Focsani',
          'Galati',
          'Giurgiu',
          'Hunedoara',
          'Iasi',
          'Miercurea-Ciuc',
          'Oradea',
          'Piatra Neamt',
          'Pitesti',
          'Ploiesti',
          'Resita',
          'Ramnicu Valcea',
          'Salcia',
          'Satu Mare',
          'Scheia',
          'Sfantu-Gheorghe',
          'Sibiu',
          'Slatina',
          'Slobozia',
          'Suceava',
          'Timisoara',
          'Tulcea',
          'Targoviste',
          'Targu Jiu',
          'Targu-Mures',
          'Vaslui',
          'Zalau'
          ]
