"""empty message

Revision ID: 026acef95f66
Revises: c206a7c71be0
Create Date: 2020-01-08 15:07:41.575002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026acef95f66'
down_revision = 'c206a7c71be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneNumber', sa.String(length=255), server_default='', nullable=False))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phoneNumber')
    # ### end Alembic commands ###
