"""empty message

Revision ID: c206a7c71be0
Revises: d6959e0bb9db
Create Date: 2020-01-07 19:59:17.826594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c206a7c71be0'
down_revision = 'd6959e0bb9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idParkingSpot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idParkingSpot'], ['parking_spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUser'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_offs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('idParkingSpot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idParkingSpot'], ['parking_spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_offs')
    op.drop_table('bookings')
    op.drop_table('parking_spots')
    # ### end Alembic commands ###
